POST http://localhost:5000/api/project/register
Content-Type: application/json

{
  "projectId": "e1fbe9d7-5a50-4c06-a20d-25897e5dacca",
  "memberIds": [
    "2b3c4d5e-6789-01bc-def0-2345678901bc"
  ]
}